-- 코드를 입력하세요
SELECT DATE_FORMAT(os.SALES_DATE, "%Y") AS YEAR, DATE_FORMAT(os.SALES_DATE, "%m") AS MONTH
     , ui.GENDER, COUNT(DISTINCT os.USER_ID) AS USERS
FROM ONLINE_SALE AS os
  INNER JOIN USER_INFO AS ui ON os.USER_ID = ui.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC
