# 대여기간 조건을 만족하는 CAR_ID 
# 30일 대여시 할인율과 차 종류
# 차 종류별 데일리 요금
# 위 세 테이블을 합쳐서 차 종류별로 30일 대여시 FEE 출력
SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE(DAILY_FEE*30*(1-DISCOUNT_RATE*0.01), 0) AS FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE 
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_TYPE REGEXP '세단|SUV') AS C
INNER JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE = '30일 이상') AS D ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') < '2022-12-01' 
                         AND DATE_FORMAT(END_DATE, '%Y-%m-%d') > '2022-11-01')
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC