-- 코드를 입력하세요
SELECT CART_ID
FROM (SELECT CART_ID, GROUP_CONCAT(NAME) AS NAME
      FROM CART_PRODUCTS
      WHERE NAME LIKE "Milk" OR NAME LIKE "Yogurt"
      GROUP BY CART_ID) AS C
WHERE NAME LIKE "%Milk%" AND NAME LIKE "%Yogurt%"