-- 코드를 입력하세요
SELECT T2.FOOD_TYPE, T2.REST_ID, T2.REST_NAME, T2.FAVORITES
FROM (
      SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE
) AS T1 INNER JOIN REST_INFO AS T2 ON T1.FOOD_TYPE = T2.FOOD_TYPE AND T1.FAVORITES = T2.FAVORITES
ORDER BY T2.FOOD_TYPE DESC