SELECT CONCAT('/home/grep/src/', T2.BOARD_ID, '/', T2.FILE_ID, T2.FILE_NAME, T2.FILE_EXT) AS FILE_PATH
FROM (SELECT * 
      FROM USED_GOODS_BOARD 
      ORDER BY VIEWS DESC 
      LIMIT 1) AS T1
INNER JOIN USED_GOODS_FILE AS T2 ON T1.BOARD_ID = T2.BOARD_ID
ORDER BY T2.FILE_ID DESC