-- 코드를 입력하세요
# SELECT *
# FROM MEMBER_PROFILE AS T1
#       INNER JOIN (
#                   SELECT MEMBER_ID, COUNT(*)
#                   FROM REST_REVIEW
#                   GROUP BY MEMBER_ID
#                  ) AS RR ON MP.MEMBER_ID = RR.MEMBER_ID) AS T1
  -- RIGHT JOIN REST_REVIEW AS T2 ON MEMBER_ID = T2.MEMBER_ID

SELECT T2.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS RR
JOIN (
    SELECT MEMBER_ID, COUNT(*) AS ID_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY ID_COUNT DESC
    LIMIT 1
     ) AS T1 ON RR.MEMBER_ID = T1.MEMBER_ID
JOIN (
    SELECT MEMBER_ID, MEMBER_NAME
    FROM MEMBER_PROFILE
     ) AS T2 ON RR.MEMBER_ID = T2.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
     
