-- 코드를 입력하세요
# SELECT PRICE 
# FROM PRODUCT
# WHERE PRICE % 10000 = 0
# GROUP BY PRICE // 10000

SELECT CASE
         WHEN PRICE < 10000 THEN 0 ELSE TRUNCATE(PRICE, -4)
       END AS PRODUCT_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRODUCT_GROUP
ORDER BY PRODUCT_GROUP
