-- 코드를 입력하세요
# SELECT CASE
#          WHEN PRICE < 10000 THEN 0 ELSE TRUNCATE(PRICE, -4)
#        END AS PRODUCT_GROUP, COUNT(*) AS PRODUCTS
# FROM PRODUCT
# GROUP BY PRODUCT_GROUP
# ORDER BY PRODUCT_GROUP

SELECT CASE
         WHEN PRICE < 10000 THEN 0 ELSE LEFT(PRICE, 1) * 10000
       END AS PRODUCT_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRODUCT_GROUP
ORDER BY PRODUCT_GROUP