-- 코드를 입력하세요
SELECT T1.PRODUCT_CODE, T1.PRICE * T2.AMOUNT AS SALES
FROM PRODUCT AS T1
 INNER JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
             FROM OFFLINE_SALE
             GROUP BY PRODUCT_ID) AS T2 ON T1.PRODUCT_ID = T2.PRODUCT_ID
ORDER BY SALES DESC, T1.PRODUCT_CODE