# -- 코드를 입력하세요
# SELECT TR.HISTORY_ID,
#        IF (TR.DURATION_TYPE IS NULL, FLOOR(TR.RENTAL_DATE*TC.DAILY_FEE),
#                                      FLOOR(TR.RENTAL_DATE*TC.DAILY_FEE*TD.DISCOUNT)) AS FEE
# FROM (SELECT HISTORY_ID, CAR_ID, (DATEDIFF(END_DATE, START_DATE) + 1) AS RENTAL_DATE,
#              CASE 
#                 WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'
#                 WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상'
#                 WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 THEN '7일 이상' ELSE NULL
#              END AS DURATION_TYPE
#       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS TR
#   INNER JOIN CAR_RENTAL_COMPANY_CAR AS TC ON TR.CAR_ID = TC.CAR_ID
#   LEFT JOIN (SELECT CAR_TYPE, DURATION_TYPE,
#                (1 - DISCOUNT_RATE*0.01) AS DISCOUNT
#                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN)
#              AS TD ON TC.CAR_TYPE = TD.CAR_TYPE AND TR.DURATION_TYPE = TD.DURATION_TYPE
# WHERE TC.CAR_TYPE = "트럭"
# ORDER BY FEE DESC

SELECT TR.HISTORY_ID,
       IF (TR.DURATION_TYPE IS NULL, FLOOR(TR.RENTAL_DATE*TC.DAILY_FEE),
                                     FLOOR(TR.RENTAL_DATE*TC.DAILY_FEE*TD.DISCOUNT)) AS FEE
FROM (SELECT *, (DATEDIFF(END_DATE, START_DATE) + 1) AS RENTAL_DATE,
             CASE 
                WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'
                WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상'
                WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 THEN '7일 이상' ELSE NULL
             END AS DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS TR
  INNER JOIN CAR_RENTAL_COMPANY_CAR AS TC ON TR.CAR_ID = TC.CAR_ID
  LEFT JOIN (SELECT CAR_TYPE, DURATION_TYPE,
                    (1 - DISCOUNT_RATE*0.01) AS DISCOUNT
             FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN)
             AS TD ON TC.CAR_TYPE = TD.CAR_TYPE AND TR.DURATION_TYPE = TD.DURATION_TYPE
WHERE TC.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC