-- 코드를 입력하세요
# SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT AS FP
#      INNER JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
# WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
# ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID


# (SELECT *
# FROM FOOD_PRODUCT AS FP
#   LEFT JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID)

# UNION ALL

# (SELECT *
# FROM FOOD_PRODUCT AS FP
#   RIGHT JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
#   WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05')


SELECT T1.PRODUCT_ID, T1.PRODUCT_NAME, T2.AMOUNT * T1.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS T1 INNER JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID
) AS T2 ON T1.PRODUCT_ID = T2.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, T2.PRODUCT_ID


# SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
# FROM FOOD_ORDER
# WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
# GROUP BY PRODUCT_ID
