-- 코드를 입력하세요
SELECT ii.INGREDIENT_TYPE, SUM(fh.TOTAL_ORDER)
FROM FIRST_HALF AS fh
  INNER JOIN ICECREAM_INFO AS ii ON fh.FLAVOR = ii.FLAVOR
GROUP BY ii.INGREDIENT_TYPE
ORDER BY SUM(fh.TOTAL_ORDER) ASC
