-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, 
       DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM (SELECT * FROM BOOK WHERE CATEGORY = "경제") AS B
  INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE