-- 코드를 입력하세요
SELECT DISTINCT T1.CAR_ID
FROM (SELECT *
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE MONTH(START_DATE) = "10") AS T1
INNER JOIN CAR_RENTAL_COMPANY_CAR AS T2 ON T1.CAR_ID = T2.CAR_ID
WHERE T2.CAR_TYPE = "세단"
ORDER BY T1.CAR_ID DESC